#!/usr/bin/env python3
"""Split the combined Game Server dashboard into one dashboard per row.

    python3 split_dashboards.py            # writes dashboards/king-teenpatti-<slug>.json
    python3 split_dashboards.py --check    # exit 1 if any output file is stale

The combined dashboard (dashboards/king-teenpatti.json, 111 panels) stays the
all-in-one overview; each row also becomes its own dashboard so a single
concern — the host, the Go runtime, sockets, the game, latency, PostgreSQL,
nginx, Redis — opens on one screen. Everything is derived from the combined
file, so edit that one and rerun this: a hand edit to a split file is lost.

Each split dashboard keeps the combined one's variables (the `datname` one
only where a panel uses it), its restart annotation, the runbook link and the
"King Teen Patti dashboards" drop-down (a dashboards-type link on the shared
tag), so hopping between them is one click. Panel ids are kept, so a link to
a panel in the combined dashboard finds the same panel here.
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, "dashboards", "king-teenpatti.json")
OUT_DIR = os.path.join(HERE, "dashboards")

# Row title in the combined dashboard → (uid suffix, dashboard title suffix, description).
ROWS = {
    "System": ("system", "System", "Host CPU, memory, swap, disk, load, network, file descriptors and TCP (node_exporter)."),
    "Runtime": ("runtime", "Runtime (Go)", "The game server process: memory, goroutines, GC, scheduler latency, CPU, network I/O (game_server_*)."),
    "WebSockets": ("sockets", "WebSockets", "Connected sockets, connections, reconnects, messages and emits by event, socket errors by code (Requirement 35b)."),
    "Multiplayer Game": ("game", "Game", "Players, tables, games started/completed/abandoned, moves, invalid moves, timeouts, kicks, chat, chips paid out (Requirement 35c)."),
    "Latency": ("latency", "Latency", "Move, creation, join, state-update, hand-start, settlement and DB transaction percentiles (Requirement 35d)."),
    "PostgreSQL": ("postgres", "PostgreSQL", "Connections, queries, transactions, cache hit ratio, locks, deadlocks, database size and the app-side pool (postgres_exporter, Requirement 35e)."),
    "Nginx": ("nginx", "Nginx", "Connection states, requests, 5xx, and the game server's HTTP responses and P95 by route (nginx-prometheus-exporter, Requirement 35g)."),
    "Live state (Redis)": ("redis", "Redis (live state)", "The live store: operation latency and rate, errors, reconcile results, restore counts, Redis memory, clients, keyspace and persistence."),
}

DASHBOARDS_LINK = {
    "type": "dashboards", "tags": ["king-teenpatti"], "asDropdown": True, "includeVars": False,
    "keepTime": True, "title": "King Teen Patti dashboards", "icon": "external link", "targetBlank": False,
}


def groups(panels):
    """Yield (row title, [panels]) in file order. Panels sit at top level after
    their row (expanded rows); a collapsed row would carry them inside."""
    current, bucket = None, []
    for p in panels:
        if p.get("type") == "row":
            if current is not None:
                yield current, bucket
            current, bucket = p["title"], list(p.get("panels", []))
        elif current is not None:
            bucket.append(p)
    if current is not None:
        yield current, bucket


def uses_var(panels, name):
    needle = re.compile(r"\$\{?" + re.escape(name) + r"\b")
    return any(needle.search(json.dumps(p)) for p in panels)


def split(source):
    combined = json.load(open(source))
    out = {}
    for title, panels in groups(combined["panels"]):
        if title not in ROWS:
            raise SystemExit(f"row {title!r} has no entry in ROWS — add one")
        suffix, name, description = ROWS[title]
        top = min(p["gridPos"]["y"] for p in panels)
        moved = []
        for p in panels:
            q = json.loads(json.dumps(p))
            q["gridPos"]["y"] -= top
            moved.append(q)
        templating = [v for v in combined["templating"]["list"]
                      if v.get("type") == "datasource" or uses_var(panels, v["name"])]
        links = [DASHBOARDS_LINK] + [l for l in combined.get("links", []) if l.get("type") != "dashboards"]
        d = {
            "uid": f"king-teenpatti-{suffix}",
            "title": f"King Teen Patti — {name}",
            "description": f"{description} One row of the combined Game Server dashboard, generated by split_dashboards.py — edit king-teenpatti.json, not this file.",
            "tags": sorted(set(combined.get("tags", [])) | {"split"}),
            "timezone": combined.get("timezone", "browser"),
            "editable": True,
            "graphTooltip": combined.get("graphTooltip", 1),
            "liveNow": False,
            "refresh": combined.get("refresh", "10s"),
            "schemaVersion": combined.get("schemaVersion", 39),
            "version": 1,
            "fiscalYearStartMonth": 0,
            "weekStart": "",
            "time": combined.get("time", {"from": "now-1h", "to": "now"}),
            "timepicker": combined.get("timepicker", {}),
            "links": links,
            "annotations": combined.get("annotations", {"list": []}),
            "templating": {"list": templating},
            "panels": moved,
        }
        out[os.path.join(OUT_DIR, f"king-teenpatti-{suffix}.json")] = d
    return out


def render(d):
    return json.dumps(d, indent=2, ensure_ascii=False) + "\n"


def main():
    check = "--check" in sys.argv
    stale = 0
    for path, d in split(SOURCE).items():
        text = render(d)
        if check:
            if not os.path.exists(path) or open(path).read() != text:
                print(f"stale: {os.path.relpath(path, HERE)}")
                stale += 1
            continue
        with open(path, "w") as f:
            f.write(text)
        print(f"wrote {os.path.relpath(path, HERE)}: {len(d['panels'])} panels, vars {[v['name'] for v in d['templating']['list']]}")
    if check:
        print("up to date" if not stale else f"{stale} stale file(s); rerun without --check")
        sys.exit(1 if stale else 0)


if __name__ == "__main__":
    main()
