#!/usr/bin/env python3
"""The SQL that moves the catalogue's rows from their R2 locations back to the
Google Drive URLs (or this server's /levels/ paths) they named before the move
to R2 (1 Oct 2026).

A rollback to a go-server tag older than the move needs it BEFORE that tag
boots: the older seed names the Drive URLs, and finding the rows at their R2
locations it would insert every profile picture, table picture and emoji a
second time (their URL is the seed's conflict key), and hand every app R2
locations that no build of that age can open. After the move back, the older
seed finds its rows where it left them; a later deploy of a build with the
move moves them forward again by itself.

    python3 tools/r2/move_back_sql.py > move-back.sql
    sudo -u postgres psql gameplay -v ON_ERROR_STOP=1 -f move-back.sql

Reads drive-to-r2.tsv beside this script (the move's record: each source URL
and the key its file was copied to). Only a row still at exactly a location
the move made is moved, and a unique column only where no row already holds
the source; an owner's own URL is never touched. One transaction.
"""

import argparse
import csv
import os

BASE = "https://a91cb23b3b93a35dd9ea50db7b855e18.r2.cloudflarestorage.com/king-teenpatti/"

# Each table the move touched, its columns that name art, and whether the
# column is UNIQUE (the seed's conflict key).
COLUMNS = {
    "profile_pictures": [("asset_url", True)],
    "table_pictures": [("day_asset_url", True), ("night_asset_url", False)],
    "emojis": [("asset_url", True)],
    "badges": [("asset_url", False)],
    "player_levels": [("asset_url", False)],
}

STAMP = "(EXTRACT(EPOCH FROM now()) * 1000)::bigint"


def quote(s):
    return "'" + s.replace("'", "''") + "'"


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--mapping", default=os.path.join(here, "drive-to-r2.tsv"))
    ap.add_argument("--base", default=BASE, help="the bucket's location prefix, ending in /")
    args = ap.parse_args()

    pairs = {table: [] for table in COLUMNS}
    with open(args.mapping, encoding="utf-8") as f:
        for row in csv.DictReader(f, delimiter="\t"):
            pairs[row["table"]].append((args.base + row["key"], row["source_url"]))

    out = ["-- Generated by tools/r2/move_back_sql.py from %s." % os.path.basename(args.mapping),
           "BEGIN;", "SET LOCAL statement_timeout = '30s';", ""]
    for table, columns in COLUMNS.items():
        if not pairs[table]:
            continue
        values = ",\n".join("    (%s, %s)" % (quote(loc), quote(src)) for loc, src in sorted(pairs[table]))
        for column, unique in columns:
            guard = ""
            if unique:
                guard = "\n   AND NOT EXISTS (SELECT 1 FROM %s q WHERE q.%s = m.source)" % (table, column)
            out.append("UPDATE %s AS t\n   SET %s = m.source,\n       updated_at = %s\n  FROM (VALUES\n%s\n  ) AS m (location, source)\n WHERE t.%s = m.location%s;\n"
                       % (table, column, STAMP, values, column, guard))
    out.append("COMMIT;")
    print("\n".join(out))


if __name__ == "__main__":
    main()
