#!/usr/bin/env python3
"""Builds the architecture documents from their parts (Python 3, stdlib only).

    python3 tools/docs/architecture/build.py            # writes both files under docs/
    python3 tools/docs/architecture/build.py --check    # exit 1 if either file is out of date
    python3 tools/docs/architecture/build.py --artifact /tmp/page.html   # also the bare page content

Sources, all in this directory:
    html/p*.html   the page, in order; {{svg:<name>}} places a diagram, and
                   {{code:<path>|<caption>}} … {{/code}} wraps a code excerpt (escaped here)
    md/p*.md       the Markdown file, in order; {{mermaid:<name>}} places a diagram
    diagrams.py    the diagrams as data: one spec each, drawn as inline SVG for the
                   page and written as Mermaid for the Markdown file (diag.py does both)

docs/architecture.html and docs/ARCHITECTURE.md are OUTPUT: edit the parts, then
run this. The page needs nothing from the network but its two web fonts, and
falls back to system fonts without them.
"""
import argparse
import glob
import html
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, '..', '..', '..'))
sys.path.insert(0, HERE)
from diagrams import ALL  # noqa: E402

GENERATED = 'Generated by tools/docs/architecture/build.py: edit the parts there, not this file.'

CAPTIONS = {
    'system': ' Players reach the Go process through nginx; bots on the game host connect over loopback. The process talks to PostgreSQL and Redis, verifies sign-ins and store receipts with Google and Apple, and signs links to the art kept in R2.',
    'layers': ' Calls go down. The domain in the middle defines the interfaces it needs; the adapters under it implement them.',
    'event': " Solid arrows are calls, dashed arrows are answers. Everything between Table.Act and its return runs as one closure on the table's goroutine.",
    'join': ' The seat is reserved in the RoomManager before the table is asked, so two players are never given the same last seat.',
    'switch': ' Every check happens before the old seat is given up, and the new seat is held from the moment it is chosen.',
    'hand': ' The four table states run along the middle. The boxes above and below are waits inside a hand, each on a server clock.',
    'money': ' A bet stays in memory and Redis. PostgreSQL is written when a player packs, when a player leaves, and when the hand ends.',
    'stats': ' The numbers match the steps below.',
    'resume': ' The seat is held first; after that, the table is offered back.',
    'boot': ' Read left to right along the top, then right to left along the bottom.',
}


def read_parts(pattern):
    parts = sorted(glob.glob(os.path.join(HERE, pattern)))
    if not parts:
        raise SystemExit(f'no parts match {pattern}')
    return ''.join(open(p, encoding='utf-8').read() for p in parts)


def figure(name):
    d = ALL[name]
    return (f'<figure class="diagram"><div class="scroll">\n{d.svg()}\n</div>'
            f'<figcaption><b>{html.escape(d.title)}.</b>{html.escape(CAPTIONS.get(name, ""), quote=False)}</figcaption></figure>')


def code_blocks(text):
    def repl(m):
        path, caption, body = m.group(1).strip(), m.group(2).strip(), m.group(3).strip('\n')
        return (f'<figure class="code"><figcaption><code>{html.escape(path)}</code>'
                f'<span>{html.escape(caption)}</span></figcaption>'
                f'<pre><code>{html.escape(body, quote=False)}</code></pre></figure>')
    return re.sub(r'\{\{code:([^|}]+)\|([^}]*)\}\}\n(.*?)\n\s*\{\{/code\}\}', repl, text, flags=re.S)


def unresolved(text, what):
    left = re.findall(r'\{\{(?:svg|code|mermaid|/code)[^}]*\}\}', text)
    if left:
        raise SystemExit(f'{what}: unresolved placeholders {left[:5]}')


def page_content():
    """The page without <html>/<head>/<body>: title, fonts, style, then the body."""
    body = code_blocks(read_parts(os.path.join('html', 'p*.html')))
    body = re.sub(r'\{\{svg:(\w+)\}\}', lambda m: figure(m.group(1)), body)
    unresolved(body, 'html')
    return body


def page_document(content):
    head_end = content.index('</style>') + len('</style>')
    return ('<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
            '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n'
            f'<!-- {GENERATED} -->\n'
            + content[:head_end] + '\n</head>\n<body>\n' + content[head_end:].lstrip('\n') + '</body>\n</html>\n')


def markdown():
    body = read_parts(os.path.join('md', 'p*.md'))
    body = re.sub(r'\{\{mermaid:(\w+)\}\}', lambda m: '```mermaid\n' + ALL[m.group(1)].mermaid() + '\n```', body)
    unresolved(body, 'markdown')
    title, rest = body.split('\n', 1)
    return f'{title}\n\n<!-- {GENERATED} -->\n{rest}'


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--check', action='store_true', help='write nothing; exit 1 if a document is out of date')
    ap.add_argument('--artifact', metavar='PATH', help='also write the page content alone (no html/head/body) to PATH')
    args = ap.parse_args()

    content = page_content()
    outputs = {
        os.path.join(REPO, 'docs', 'architecture.html'): page_document(content),
        os.path.join(REPO, 'docs', 'ARCHITECTURE.md'): markdown(),
    }
    stale = []
    for path, text in outputs.items():
        current = open(path, encoding='utf-8').read() if os.path.exists(path) else None
        if current == text:
            continue
        stale.append(os.path.relpath(path, REPO))
        if not args.check:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, 'w', encoding='utf-8') as f:
                f.write(text)
    if args.artifact:
        with open(args.artifact, 'w', encoding='utf-8') as f:
            f.write(content)
    if args.check and stale:
        print('out of date:', ', '.join(stale))
        return 1
    for path, text in outputs.items():
        print(f'{os.path.relpath(path, REPO)}: {len(text):,} bytes' + (' (written)' if os.path.relpath(path, REPO) in stale and not args.check else ''))
    return 0


if __name__ == '__main__':
    sys.exit(main())
